[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501

[theme]
primaryColor = "#0B3A5B"
backgroundColor = "#EEF6FB"
secondaryBackgroundColor = "#F7FBFF"
textColor = "#10202B"
font = "sans serif"
